### ISSUE TITLE
Update organization name

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/diffbot2_simulation#4]

**Comment by caioaamaral** [comment]
For some odd reason, badge is not broken even if path doesn't exists:
`![Ament Lint](https://github.com/open-br/diffbot2_simulation/workflows/Ament%20Lint/badge.svg?branch=main)`

**Comment by mateus-amarante** [comment]
It is because GitHub maintains the old name valid until someone else request to use this name

**Comment by caioaamaral** [comment]
@mateus-amarante #4 fix this issue IMO, what you think?

**Comment by mateus-amarante** [comment]
I think you meant that #8 fix #4. I agree.
